### ISSUE TITLE
Stepper: Remove italics from inactive bullets

### ISSUE THREAD

**Issue by miggol** [DH-IT-Portal-Development/bootstrap-theme#6]
The "inactive" class currently applies to the `.stepper-item` element and makes all text for said item render in italics. This looks weird for the item numbers and I'm presuming it isn't intentional:

![image](https://user-images.githubusercontent.com/7064137/234221469-5b5714c0-d452-4057-8119-02c28aa3936f.png)

Desired change is that for inactive stepper items, only the item title is in italics, while the stepper number looks just like an active item:

![image](https://user-images.githubusercontent.com/7064137/234222585-d95a884b-449f-42b6-8426-73fde9067483.png)

(Forced with `font-style: normal;` here)

**Comment by tymees** [comment]
Fixed in 1.3.1, which is included in the DSC 3.0.2 release. (Not yet in develop, needs backmerging which I'll somewhere next week at the latest)
